/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simple.gradle.java.app;

public class App {
    public static int getSum(int num1, int num2) {
        return num1+num2;

    }

    public static void main(String[] args) {
            System.out.println("Sum is " + getSum(4,5));
    }
}
